name: trivy-plugin-postee
on:
  workflow_dispatch:
env:
  ORGANIZATION: krol
  APP: helloworld
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Trivy
        run: |
          export TRIVY_VERSION=$(wget -qO - "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
          echo $TRIVY_VERSION
          wget --no-verbose https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz -O - | tar -zxvf -
          echo "$PWD/" >> $GITHUB_PATH

      - name: Send results to Postee
        env:
          POSTEE: ${{ secrets.POSTEE_SERVER }}
        run: |
          RESULTS="trivy-results.json"
          trivy plugin install github.com/aquasecurity/trivy-plugin-kubectl
          trivy webhook -- --url=$POSTEE -- image alpine:3.10
        # postee-server:8082